# Generated by Django 5.2.13 on 2026-04-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0003_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='size',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
