# Generated by Django 5.2.13 on 2026-04-17 00:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0004_alter_waterbottle_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='current_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
